### ISSUE TITLE
Compatibility for TRIQS 1.4

### ISSUE THREAD

**Issue by henhans** [TRIQS/ctint_tutorial#1]
Dear TRIQS team,

I'm trying to compile this tutorial using triqs version 1.4. It shows several compile errors. I try to solve them with some modifications described in below paragraph. The code is compiled, but it does not reproduce the previous results in ipytriqs_notebook "dmft_bethe.ipynb". I'm wondering if I did something wrong with the modification? especially the `gt[0](0,0)`, `boost::mpi::communicator` and `all_reduce` as described below. 

Here is the modifications:

1.The first error is the complex to double error in the return in struct` g0bar_tau{ ........ return 1.0 +   gt[0](0, 0)  - (0.5 + (2 * (s == x.s ? 1 : 0) - 1) * delta .....}` in ctint.cpp at line16. I changed it to `gt[0](0, 0).real()` and the error disappear.

2.The second error is the compatibility between `triqs::mpi::communicator` and `boost::mpi::communicator`, as well as the `boost::mpi::all_reduce(....)` compatibility. Before modification, the error shows:
` ../../c++/libctint_tutorial_c.so: undefined reference to triqs::mpi::communicator::operator boost::mpi::communicator() const' `

I try to solve this by replacing `boost::mpi::comunicator` with `triqs::mpi::communicator`, and replace `boost::mpi::all_reduce(c, Mw, Mw, std14::plus<>())` with `triqs::mpi::mpi_all_reduce(Mw,c)`. After the modification the code is compiled, but the notebook in /example/dmft_bethe.ipynb does not reproduce the previous results.

Here is the ipytriqs_notebook results with the previous results:
http://nbviewer.jupyter.org/github/henhans/ctint_tutorial/blob/master/examples/dmft_bethe.ipynb
and here is the modified code
https://github.com/henhans/ctint_tutorial

Thank you.
Tsung-Han

**Comment by parcollet** [comment]
Indeed, we did not port ctint_tutorial to the master branch yet.
To be done, and added to Jenkins.

**Comment by krivenko** [comment]
Should be fixed by commits 53ef712f3a7833ae12b28d6a5627b6550270f52d and 002f3fb7cd07389f0b8752b8b65eec73e27f036b.
Please, add to Jenkins and then close.

**Comment by henhans** [comment]
Dear Dr. Krivenko. It shows the following error message while compiling:
```
Scanning dependencies of target ctint_tutorial_c

[ 14%] Building CXX object c++/CMakeFiles/ctint_tutorial_c.dir/ctint.cpp.o
Linking CXX shared library libctint_tutorial_c.so
[ 14%] Built target ctint_tutorial_c
[ 28%] Generating ctint_tutorial_desc.py, ctint_tutorial_wrap.cpp, ../include/pytriqs/converters/ctint_tutorial.hpp
Traceback (most recent call last):
  File "/home/henhans/my_ctint/ctint_tutorial/build/python/ctint_tutorial_desc.py", line 6, in <module>
    module = module_(full_name = "pytriqs.applications.impurity_solvers.ctint_tutorial", doc = "", app_name = "pytriqs.applications.impurity_solvers.ctint_tutorial")
TypeError: __init__() got an unexpected keyword argument 'app_name'
python/CMakeFiles/ctint_tutorial.dir/build.make:53: recipe for target 'python/ctint_tutorial_desc.py' failed
make[2]: *** [python/ctint_tutorial_desc.py] Error 1
CMakeFiles/Makefile2:129: recipe for target 'python/CMakeFiles/ctint_tutorial.dir/all' failed
make[1]: *** [python/CMakeFiles/ctint_tutorial.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
```

It seems the module_() in ctint_tutorial_desc.py has unrecognized argument. But the ctint.cpp modification works now. I could reproduce the previous results using the old ctint_tutorial_desc.py 
Thank you!

**Comment by krivenko** [comment]
Dear Tsung-Han,
Are you using the most recent version of the library (master branch)?

**Comment by henhans** [comment]
Dear Dr. Krivenko, 
Thank you! The tutorial is compiled and can reproduce the previous results after I update to latest TRIQS master.
